version: '2'
services:

  phish:
    image: gophish/gophish:latest
    ports:
      - 3333:3333
      - 8083:80

  mailcatcher:
    image: schickling/mailcatcher
    ports: 
      - 1080:1080
      - 1025:1025

